### ISSUE TITLE
error(prover_fri): Error occurred while processing FriCpuProver job: "unsatisfied"

### ISSUE THREAD

**Issue by ChengYueJia** [matter-labs/zksync-era#1008]
#### 📝 Description

When trying to generate fri proof, meets error the evm circuit unsatisfied.

#### 🔄 Reproduction Steps

Follow https://github.com/matter-labs/zksync-era/blob/9b701e70a4046cf9a84ce264d71e4ae0e8835f88/prover/prover_fri/README.md to run the whole node and

#### 🤔 Expected Behavior

Everything works fine.

#### 😯 Current Behavior

As logs shows.

#### 🖥️ Environment

* Ubuntu 22.04
* release core: 20.5.2
* cdca2606e0b8f4d14af8560321c6476edb14d395

#### 📎 Log Output

```
job: FriProverJobMetadata { id: 6, block_number: L1BatchNumber(1), circuit_id: 1, aggregation_round: BasicCircuits, sequence_number: 5, depth: 0, is_node_final_proof: false }
[/mnt/rust/git/checkouts/era-boojum-eee09114f0ca3855/93b5e0f/src/cs/implementations/prover.rs:218] interactive_soundness = 106
[/mnt/rust/git/checkouts/era-boojum-eee09114f0ca3855/93b5e0f/src/cs/implementations/prover.rs:280] quotient_degree = 8
[/mnt/rust/git/checkouts/era-boojum-eee09114f0ca3855/93b5e0f/src/cs/implementations/prover.rs:622] total_num_lookup_argument_terms = 9
[/mnt/rust/git/checkouts/era-boojum-eee09114f0ca3855/93b5e0f/src/cs/implementations/prover.rs:623] total_num_gate_terms_for_specialized_columns = 1
[/mnt/rust/git/checkouts/era-boojum-eee09114f0ca3855/93b5e0f/src/cs/implementations/prover.rs:624] total_num_gate_terms_for_general_purpose_columns = 414
[/mnt/rust/git/checkouts/era-boojum-eee09114f0ca3855/93b5e0f/src/cs/implementations/prover.rs:625] num_intermediate_partial_product_relations = 19
thread 'tokio-runtime-worker' panicked at /mnt/rust/git/checkouts/era-boojum-eee09114f0ca3855/93b5e0f/src/cs/implementations/prover.rs:1444:17:
unsatisfied
stack backtrace:
   0:     0x557c1df61cfc - std::backtrace_rs::backtrace::libunwind::trace::h68b3f03db065435f
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557c1df61cfc - std::backtrace_rs::backtrace::trace_unsynchronized::hcc29d957a519c467
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557c1df61cfc - std::sys_common::backtrace::_print_fmt::h51e5567c7446b80e
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x557c1df61cfc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h54890bb4d0b3c330
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557c1df8f4dc - core::fmt::rt::Argument::fmt::heae7cd8ccc900aeb
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/fmt/rt.rs:138:9
   5:     0x557c1df8f4dc - core::fmt::write::hc761729f1163b685
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/fmt/mod.rs:1094:21
   6:     0x557c1df5e24e - std::io::Write::write_fmt::hd8de790e313b58ee
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/io/mod.rs:1714:15
   7:     0x557c1df61ae4 - std::sys_common::backtrace::_print::h1b2adaff5c947b3b
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x557c1df61ae4 - std::sys_common::backtrace::print::hf6a9b81f93e62890
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x557c1df6391a - std::panicking::panic_hook_with_disk_dump::{{closure}}::h663629ab1a73f13e
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:278:22
  10:     0x557c1df63607 - std::panicking::panic_hook_with_disk_dump::h7dc7628c0cba33b1
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:312:9
  11:     0x557c1df63f1b - std::panicking::default_hook::h4cb3ec769d1db09c
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:239:5
  12:     0x557c1df63f1b - std::panicking::rust_panic_with_hook::hdd1521f6ef2543b7
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:729:13
  13:     0x557c1df63dd1 - std::panicking::begin_panic_handler::{{closure}}::h7c4ede115dee30b0
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:619:13
  14:     0x557c1df62226 - std::sys_common::backtrace::__rust_end_short_backtrace::habd7cadfbd319a50
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:170:18
  15:     0x557c1df63b62 - rust_begin_unwind
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:617:5
  16:     0x557c1cfd3163 - core::panicking::panic_fmt::hb85e049a4301ecd3
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/panicking.rs:67:14
  17:     0x557c1d118d3b - boojum::cs::implementations::prover::<impl boojum::cs::implementations::reference_cs::CSReferenceAssembly<F,P,CFG>>::prove_cpu_basic::h482688d492b0b878
  18:     0x557c1d03bd13 - boojum::cs::implementations::convenience::<impl boojum::cs::implementations::reference_cs::CSReferenceAssembly<F,P,CFG>>::prove_from_precomputations::hbb627de9d8b4c9f7
  19:     0x557c1d4add96 - zkevm_test_harness::prover_utils::prove_base_layer_circuit::h50d7bd75276a8559
  20:     0x557c1d3083b0 - zksync_prover_fri::prover_job_processor::Prover::prove::hc8ad9d7202bb1841
  21:     0x557c1d490f1f - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hb13d423403faa507
  22:     0x557c1d27ac09 - tokio::runtime::task::core::Core<T,S>::poll::hf86103c4eec89cba
  23:     0x557c1d281cac - tokio::runtime::task::harness::Harness<T,S>::poll::h703190abeebda57a
  24:     0x557c1defb81d - tokio::runtime::blocking::pool::Inner::run::h3a52a47465a3be76
  25:     0x557c1def2215 - std::sys_common::backtrace::__rust_begin_short_backtrace::hddf516c1e5974791
  26:     0x557c1def04e9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8024abcb8974d092
  27:     0x557c1df66ca5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7bbddabb40181918
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/alloc/src/boxed.rs:2007:9
  28:     0x557c1df66ca5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e41f7977be0d993
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/alloc/src/boxed.rs:2007:9
  29:     0x557c1df66ca5 - std::sys::unix::thread::Thread::new::thread_start::h6eb72cf9b874b24b
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys/unix/thread.rs:108:17
  30:     0x7f80ce094ac3 - <unknown>
  31:     0x7f80ce126850 - <unknown>
  32:                0x0 - <unknown>
2024-02-05T03:07:02.073245Z ERROR zksync_queued_job_processor: Error occurred while processing FriCpuProver job 6: "unsatisfied"
2024-02-05T03:07:02.076103Z  INFO zksync_prover_fri_utils: Started processing prover job: FriProverJobMetadata { id: 80, block_number: L1BatchNumber(1), circuit_id: 12, aggregation_round: LeafAggregation, sequence_number: 0, depth: 0, is_node_final_proof: false }
```

**Comment by ChengYueJia** [comment]
@EmilLuta hi, I've tried to run the latest code. ( The latest code commit revision is : 5087121db54d49bc5268e3b77790d3315976b69a)

And meet a different error, to see more: https://github.com/matter-labs/zksync-era/issues/1084
We can move #1084 to discuss.
