### ISSUE TITLE
Cannot verify the account contract

### ISSUE THREAD

**Issue by ChiHaoLu** [matter-labs/zksync-era#1629]
#### 📝 Description

It cannot verify the account contract with zkSync hardhat.

#### 🔄 Reproduction Steps

```typescript
const aaArtifact = await deployer.loadArtifact("Account");
  const constructorArgs = abiCoder.encode(
    ["bytes32", "address"],
    [salt, ownerAddress]
  );
  const fullContractSource = `${aaArtifact.sourceName}:${aaArtifact.contractName}`;
  if (hre.network.config.verifyURL) {
    console.log(`Requesting contract verification...`);
    for (let i = 0; i < 50; i++) {
      console.log(i);
      try {
        await verifyContract({
          address: accountAddress,
          contract: fullContractSource,
          constructorArguments: constructorArgs,
          bytecode: aaArtifact.bytecode,
        });
        break;
      } catch (e) {
        console.log(e)
        await timeout(3000);
      }
    }
  }
```

The factory is:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import "@matterlabs/zksync-contracts/l2/system-contracts/Constants.sol";
import "@matterlabs/zksync-contracts/l2/system-contracts/libraries/SystemContractsCaller.sol";

contract AAFactory {
    bytes32 public aaBytecodeHash;

    constructor(bytes32 _aaBytecodeHash) {
        aaBytecodeHash = _aaBytecodeHash;
    }

    function deployAccount(
        bytes32 salt,
        address owner
    ) external returns (address accountAddress) {
        (bool success, bytes memory returnData) = SystemContractsCaller
            .systemCallWithReturndata(
                uint32(gasleft()),
                address(DEPLOYER_SYSTEM_CONTRACT),
                uint128(0),
                abi.encodeCall(
                    DEPLOYER_SYSTEM_CONTRACT.create2Account,
                    (
                        salt,
                        aaBytecodeHash,
                        abi.encode(owner),
                        IContractDeployer.AccountAbstractionVersion.Version1
                    )
                )
            );
        require(success, "Deployment failed");

        (accountAddress) = abi.decode(returnData, (address));
    }
}
```

#### 🤔 Expected Behavior

Expect it to verify successfully.

#### 😯 Current Behavior

```
ZkSyncVerifyPluginError: The address 0x7d9Cc156be13a4690eCcC840179c2771670E9AF4 has no bytecode. Is the contract deployed to this network?
  The selected network is zkSyncSepoliaTestnet.
    at retrieveContractBytecode (/Users/chihaolu/Desktop/imToken/zkSync-Payment-Mininal-Demo/node_modules/@matterlabs/hardhat-zksync-verify/src/utils.ts:75:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OverriddenTaskDefinition.verifyContract [as _action] (/Users/chihaolu/Desktop/imToken/zkSync-Payment-Mininal-Demo/node_modules/@matterlabs/hardhat-zksync-verify/src/task-actions.ts:163:33)
    at async Environment._runTaskDefinition (/Users/chihaolu/Desktop/imToken/zkSync-Payment-Mininal-Demo/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Object.Environment.run (/Users/chihaolu/Desktop/imToken/zkSync-Payment-Mininal-Demo/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
Done!
```

#### 🖥️ Environment

```
networks: {
    zkSyncSepoliaTestnet: {
      url: "https://sepolia.era.zksync.dev",
      ethNetwork: "sepolia",
      zksync: true,
      verifyURL:
        "https://explorer.sepolia.era.zksync.dev/contract_verification",
    }
  },
```

**Comment by ChiHaoLu** [comment]
I close the issue here, and create a new issue in zkSync-hardhat.

https://github.com/matter-labs/hardhat-zksync/issues/1007
