### ISSUE TITLE
Establishment of main network nodes

### ISSUE THREAD

**Issue by mayong82** [matter-labs/zksync-era#36]
How to build the main network node? Do you have any relevant official documents for reference?

**Comment by lcgogo** [comment]
I have seen there are some the latest changes in 
https://github.com/matter-labs/zksync-era/tree/main/docs/external-node
and 
https://hub.docker.com/r/matterlabs/external-node-public/tags 

but not very clear how to run a mainnet zysync era node too.

The docs auther @shahar4 Can you help to give a simple guide?

**Comment by shahar4** [comment]
Hello! You can refer to the knowledge index in the main README which will point you to all of our documentation detailing how we run the main node and how you can too. The external node documentation shouldn't be used as it's only for the external node which is an unfinished project.

I'm very happy for suggestions if you have questions that you feel are not answered in our docs!

**Comment by dubuqingfeng** [comment]
> I have seen there are some latest changes in https://github.com/matter-labs/zksync-era/tree/main/docs/external-node and https://hub.docker.com/r/matterlabs/external-node-public/tags
> 
> but not very clear how to run a mainnet zysync era node too.
> 
> The docs auther @shahar4 Can you help to give a simple guide?

The following error is reported when running the image for reference
```
CONTRACTS_GENESIS_ROOT=0xf33801c260dccc153ea0008b8561e59c1fbf52ef77c9cd3a4bc2137b0929911a
CONTRACTS_GENESIS_BLOCK_COMMITMENT=0xb8befd758f9271cf5aa1dc5a2b8d225a5e2e85818b1c15c9ca5608ad31106032
CONTRACTS_GENESIS_ROLLUP_LEAF_INDEX=22
CHAIN_STATE_KEEPER_BOOTLOADER_HASH=0x010007794e73f682ad6d27e86b6f71bbee875fc26f5708d1713e7cfd476098d3
CHAIN_STATE_KEEPER_DEFAULT_AA_HASH=0x0100067d861e2f5717a12c3e869cfb657793b86bbb0caa05cc1421f16c5217bc
thread 'main' panicked at 'Genesis block root hash mismatch with main node: expected 0xf338…911a, got 0xbc59…ba95', /usr/src/zksync/core/bin/zksync_core/src/sync_layer/genesis.rs:46:9
stack backtrace:
   0:     0x55a54d70bbba - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a54d70bbba - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a54d70bbba - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55a54d70bbba - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55a54d73199e - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x55a54d705c85 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x55a54d70b985 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55a54d70b985 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55a54d70d5df - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x55a54d70d31b - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x55a54d70dcec - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x55a54d70da89 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0x55a54d70c06c - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55a54d70d792 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x55a54bf86993 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x55a54c162242 - zksync_external_node::main::{{closure}}::h628e1a5a6d7ee3e8
  16:     0x55a54c14bfde - tokio::runtime::park::CachedParkThread::block_on::hb316be35b5a2f9a3
  17:     0x55a54c21aca9 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h2164c96c1a9f3754
  18:     0x55a54c28af5e - tokio::runtime::runtime::Runtime::block_on::h0ee8a923255b89dc
  19:     0x55a54c2b931f - zksync_external_node::main::hd4ba10f139e95b5f
  20:     0x55a54c0a5823 - std::sys_common::backtrace::__rust_begin_short_backtrace::hef1310226ef12b95
  21:     0x55a54bfcf84d - std::rt::lang_start::{{closure}}::hb6a1fb9f54db0e61
  22:     0x55a54d6fdf7c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfa1c3687c9a20bb8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
  23:     0x55a54d6fdf7c - std::panicking::try::do_call::h0497133ebe1341e5
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  24:     0x55a54d6fdf7c - std::panicking::try::h6c3de05c7ca5d07f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  25:     0x55a54d6fdf7c - std::panic::catch_unwind::h969058ecb5334b30
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  26:     0x55a54d6fdf7c - std::rt::lang_start_internal::{{closure}}::h0de6d98cafb42a58
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
  27:     0x55a54d6fdf7c - std::panicking::try::do_call::h77301dcf43953993
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  28:     0x55a54d6fdf7c - std::panicking::try::h45b05523a2fe135a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  29:     0x55a54d6fdf7c - std::panic::catch_unwind::hd95cea544b2b9bd2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  30:     0x55a54d6fdf7c - std::rt::lang_start_internal::hd16e6ff7bf05a444
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  31:     0x55a54c2b9405 - main
  32:     0x7fcd6822409b - __libc_start_main
  33:     0x55a54bfaff3a - _start
  34:                0x0 - <unknown>
  ```

**Comment by lcgogo** [comment]
> Hello! You can refer to the knowledge index in the main README which will point you to all of our documentation detailing how we run the main node and how you can too. The external node documentation shouldn't be used as it's only for the external node which is an unfinished project.
> 
> I'm very happy for suggestions if you have questions that you feel are not answered in our docs!

Thanks for clarify, but I read 

How can I run the project? | launch.md
-- | --
How can I run the project? 	[launch.md](https://github.com/matter-labs/zksync-era/blob/main/docs/launch.md)

And the guide show run a `zk` command directly. So I jump to 

Prepare dev environment prerequisites: see

[Installing dependencies](https://github.com/matter-labs/zksync-era/blob/main/docs/setup-dev.md)

And the setup-dev.md shows run `docker-compose up -d`

After I run `docker-compose up -d`, I find it is only a local private network but not mainnet.
I read the `docker-compose.yml and there are nothing about network choice environment or something like that.

**Comment by mikhail-khalizev** [comment]
From the documentation it is not at all clear how to run the mainnet node.

Is it really difficult for developers to simply publish a working docker-compose.yml in which they just need to paste the url to Web3 L1 Ethereum? And all questions would immediately be removed.

Instead there is a docker-compose pile:
* docker-compose.yml
* docker-compose-runner.yml
* docker-compose-cpu-runner.yml
* docker-compose-gpu-runner.yml

On the face of it, it may seem that this is all for running the mainnet. But no! It turns out that these are all local nodes for debugging. At least they would be given a name like 'test-local-node' to avoid confusion.

**Comment by hatemosphere** [comment]
https://github.com/matter-labs/zksync-era/issues/15#issuecomment-1764579823
