### ISSUE TITLE
zksync-cli bridge deposit causes the server panic 

### ISSUE THREAD

**Issue by JayT106** [matter-labs/zksync-era#438]
### 🐛 Bug Report
zksync-cli bridge deposit cause the eth tx manager send error. And then the server will panic once proof got submitted to the L1.

#### 📝 Description

Deployed local dev network with gpu fri prover, finished the genesis block proof. Tries to send some eth from L1 to L2.

#### 🔄 Reproduction Steps
1. `zk init` to setup local dev net, wait the genesis block proof finished.
2. run `zksync-cli bridge deposit  [some address]`
3. check balance of the address, the address in L2 got the value transfered.
4. the server log shows send transaction nonce too low
5. Wait another block proof submitted to L1
6. server panic.

#### 🤔 Expected Behavior

the eth tx manager should sent tx without error and the server will not panic.

#### 😯 Current Behavior

not sure the transaction sent from the eth tx manager for. But it happens after the cli bridge deposit. And the server go panic later on.

#### 🖥️ Environment

zksync-era: core-v_boojnet_1.12.0
zksync-cli: 0.7.1

#### 📎 Log Output

Cli terminal
```
~$ zksync-cli bridge deposit
? Chain to use Local Dockerized node
? Amount of ETH to deposit (eg. 0.1) 100
? Private key of the sender [hidden]
? Recipient address on L2 (0x address) 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

Deposit:
 From: 0xde03a0B5963f75f1C8485B355fF6D30f3093BDE7 (L1 Local)
 To: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 (Local Dockerized node)
 Amount: 100 ETH

Sending deposit transaction...

Deposit sent:
 Transaction hash: 0xd6f472a4077354788a598b43059914be7d1a913aeef6fb5557ac54dc2c5d3f8c

Sender L1 balance after transaction: 99999999999999996796.61772155459479787 ETH
```
Zk Server log
```
2023-11-07T18:30:19.421994Z DEBUG zksync_state::postgres: Updating storage values cache from miniblock 0 to 2                                                               
2023-11-07T18:30:19.424200Z DEBUG zksync_state::postgres: Loaded 67 modified storage keys from miniblocks MiniblockNumber(1)..=MiniblockNumber(2); took 2.140489ms
2023-11-07T18:30:21.202865Z  INFO zksync_core::state_keeper::io::mempool: Getting previous L1 batch hash for L1 batch #2                                                    
2023-11-07T18:30:21.210962Z  INFO zksync_core::state_keeper::io::mempool: Got previous L1 batch hash: ad0312bb031ec4fa0becde80399ae865e8eb3f6431419ebf20882882bbe6828c for L
1 batch #2                 
2023-11-07T18:30:21.213014Z  INFO zksync_core::state_keeper::io::mempool: (l1_gas_price, fair_l2_gas_price) for L1 batch #2 is (800000008, 250000000)                       
2023-11-07T18:30:21.251783Z  INFO zksync_storage::db: Initialized RocksDB `state_keeper` at `./db/main/state_keeper` with RocksDBOptions { block_cache_capacity: None, large
_memtable_capacity: None, stalled_writes_retries: StalledWritesRetries { max_batch_size: 134217728, timeout: 10s, start_interval: 50ms, max_interval: 2s, scale_factor: 1.5 
} }                                                                                                                                                                         
2023-11-07T18:30:21.253615Z DEBUG zksync_state::rocksdb: loading storage for l1 batch number 1                                                                              
2023-11-07T18:30:21.253827Z DEBUG zksync_state::rocksdb: loading state changes for l1 batch 1
2023-11-07T18:30:21.258124Z DEBUG zksync_state::rocksdb: loading factory deps for l1 batch 1                                                                                
2023-11-07T18:30:21.262040Z  INFO zksync_state::rocksdb: Secondary storage for L1 batch #1 initialized, size is 85                                                          
2023-11-07T18:30:21.262320Z  INFO zksync_core::state_keeper::batch_executor: Starting executing batch #L1BatchNumber(2)
2023-11-07T18:30:22.284842Z  INFO zksync_core::state_keeper::io::seal_logic: Sealing miniblock 3 (L1 batch 2) with 1 (0 L2 + 1 L1) txs, 5 events, 53 reads, 20 writes       
2023-11-07T18:30:24.421760Z  INFO zksync_core::state_keeper::io::seal_logic: Sealing miniblock 4 (L1 batch 2) with 0 (0 L2 + 0 L1) txs, 1 events, 2084 reads, 14 writes     
2023-11-07T18:30:24.558120Z  INFO zksync_core::state_keeper::io::seal_logic: Sealing L1 batch 2 with 1 (0 L2 + 1 L1) txs, 1 l2_l1_logs, 6 events, 2137 reads (21 deduped), 3
4 writes (9 deduped)                                                                                                                                                        
2023-11-07T18:30:24.684966Z  INFO zksync_core::metadata_calculator::updater: Updating Merkle tree with L1 batches #2..=2                                                    
2023-11-07T18:30:24.685001Z  INFO zksync_core::metadata_calculator::updater: Processing L1 batches #2..=2
2023-11-07T18:30:24.690337Z  INFO zksync_merkle_tree::domain: Extending Merkle tree with batch #2 with 30 ops in full mode                                                  
2023-11-07T18:30:24.692586Z  INFO zksync_merkle_tree::domain: Processed batch #2; root hash is 0x4f52…ab86, 86 leaves in total, 4 initial writes, 5 repeated writes         
2023-11-07T18:30:24.693035Z  INFO zksync_core::metadata_calculator::updater: Saved witnesses for L1 batch #2 to object storage at `merkel_tree_paths_2.bin`
2023-11-07T18:30:27.753827Z  INFO loop_iteration{prover_storage=StorageProcessor { conn: Pooled connection, in_transaction: false }}: zksync_core::eth_sender::eth_tx_aggreg
ator: eth_tx with ID 4 for op commit was saved for L1 batches L1BatchNumber(2)..=L1BatchNumber(2)                                                                           
2023-11-07T18:30:27.758114Z  INFO zksync_core::metadata_calculator::updater: Updated metadata for L1 batch #2 in Postgres
2023-11-07T18:30:27.758213Z  INFO zksync_merkle_tree::domain: Flushing L1 batches #[2] to RocksDB                                                                           
2023-11-07T18:30:27.758565Z  INFO zksync_core::metadata_calculator::metrics: L1 batches #2..=2 processed in tree                                                            
2023-11-07T18:30:27.758878Z DEBUG zksync_health_check: changed health from Health { status: Ready, details: Some(Object {"leaf_count": Number(82), "mode": String("full"), "
next_l1_batch_number": Number(2), "root_hash": String("0xad0312bb031ec4fa0becde80399ae865e8eb3f6431419ebf20882882bbe6828c")}) } to Health { status: Ready, details: Some(Obj
ect {"leaf_count": Number(86), "mode": String("full"), "next_l1_batch_number": Number(3), "root_hash": String("0x4f5270483f0bf36adb361bdb2829ebc4042f0fa59f6c10ba0817013fec3
8ab86")}) }                
2023-11-07T18:30:28.750235Z  WARN loop_iteration{previous_block=L1BlockNumber(1647922)}: zksync_core::eth_sender::eth_tx_manager: Error when sending new signed tx for tx 4,
 base_fee_per_gas 10, priority_fee_per_gas: 1000000000: Ethereum gateway Error Request to ethereum gateway failed: RPC error: Error { code: ServerError(-32000), message: "n
once too low", data: None }

```
After the second compression proof submitted
Server panic log
```
[/home/crypto/.cargo/git/checkouts/solidity_plonk_verifier-d3876c5ca7686643/82f96b7/codegen/src/lib.rs:155] &serialized_proof.len() = 44                                    
2023-11-07T20:00:21.973915Z  INFO loop_iteration{prover_storage=StorageProcessor { conn: Pooled connection, in_transaction: false }}: zksync_core::eth_sender::eth_tx_aggreg
ator: eth_tx with ID 5 for op proof was saved for L1 batches L1BatchNumber(2)..=L1BatchNumber(2)                                                                            
2023-11-07T20:00:22.692519Z  WARN loop_iteration{previous_block=L1BlockNumber(1653316)}: zksync_core::eth_sender::eth_tx_manager: Error when sending new signed tx for tx 4,
 base_fee_per_gas 10, priority_fee_per_gas: 1000000000: Ethereum gateway Error Request to ethereum gateway failed: RPC error: Error { code: ServerError(-32000), message: "n
once too low", data: None }                                                                                                                                                 
2023-11-07T20:00:22.699856Z ERROR loop_iteration{previous_block=L1BlockNumber(1653316)}: zksync_core::eth_sender::eth_tx_manager: Possible block reorgs: finalized nonce inc
rease detected, but no tx receipt found for tx EthTx { id: 4, nonce: Nonce(195), contract_address: 0xf61d2e9fa5a7b7b0f70905a0d8e9144bf9b6b90f, tx_type: Commit, created_at_t
imestamp: 1699381827, predicted_gas_cost: 290136 }                                                                                                                          
2023-11-07T20:00:22.984755Z  INFO loop_iteration{prover_storage=StorageProcessor { conn: Pooled connection, in_transaction: false }}: zksync_core::eth_sender::eth_tx_aggreg
ator: eth_tx with ID 6 for op execute was saved for L1 batches L1BatchNumber(2)..=L1BatchNumber(2)                                                                          
2023-11-07T20:00:23.711160Z ERROR loop_iteration{previous_block=L1BlockNumber(1653317)}: zksync_core::eth_sender::eth_tx_manager: Possible block reorgs: finalized nonce inc
rease detected, but no tx receipt found for tx EthTx { id: 4, nonce: Nonce(195), contract_address: 0xf61d2e9fa5a7b7b0f70905a0d8e9144bf9b6b90f, tx_type: Commit, created_at_t
imestamp: 1699381827, predicted_gas_cost: 290136 }
2023-11-07T20:00:23.712432Z  INFO loop_iteration{previous_block=L1BlockNumber(1653317)}: zksync_core::eth_sender::eth_tx_manager: Resending operation 5 with base fee 10 and
 priority fee 1200000001
2023-11-07T20:00:24.722348Z ERROR loop_iteration{previous_block=L1BlockNumber(1653318)}: zksync_core::eth_sender::eth_tx_manager: Possible block reorgs: finalized nonce inc
rease detected, but no tx receipt found for tx EthTx { id: 4, nonce: Nonce(195), contract_address: 0xf61d2e9fa5a7b7b0f70905a0d8e9144bf9b6b90f, tx_type: Commit, created_at_t
imestamp: 1699381827, predicted_gas_cost: 290136 }
2023-11-07T20:00:24.723251Z  INFO loop_iteration{previous_block=L1BlockNumber(1653318)}: zksync_core::eth_sender::eth_tx_manager: Resending operation 6 with base fee 10 and
 priority fee 1200000001
2023-11-07T20:00:25.733407Z ERROR loop_iteration{previous_block=L1BlockNumber(1653319)}: zksync_core::eth_sender::eth_tx_manager: Possible block reorgs: finalized nonce inc
rease detected, but no tx receipt found for tx EthTx { id: 4, nonce: Nonce(195), contract_address: 0xf61d2e9fa5a7b7b0f70905a0d8e9144bf9b6b90f, tx_type: Commit, created_at_t
imestamp: 1699381827, predicted_gas_cost: 290136 }
2023-11-07T20:00:25.740173Z ERROR loop_iteration{previous_block=L1BlockNumber(1653319)}: zksync_core::eth_sender::eth_tx_manager: Eth tx failed EthTx { id: 5, nonce: Nonce(
196), contract_address: 0xf61d2e9fa5a7b7b0f70905a0d8e9144bf9b6b90f, tx_type: PublishProofOnchain, created_at_timestamp: 1699387221, predicted_gas_cost: 1007000 }, Receipt {
 transaction_hash: 0x7a8e09f51799df29fc0b3a9f6a688978e7c17353cce1967d2e85cf06d97b4463, transaction_index: 0, block_hash: Some(0xcce66d4fca250641a88908bb010435c544de757c1a06
ec880ed9560eaf05f642), block_number: Some(1653319), from: 0xde03a0b5963f75f1c8485b355ff6d30f3093bde7, to: Some(0xf61d2e9fa5a7b7b0f70905a0d8e9144bf9b6b90f), cumulative_gas_u
sed: 86513, gas_used: Some(86513), contract_address: None, logs: [], status: Some(0), root: None, logs_bloom: 0x000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, transaction_type: Some(2), effective_gas_price: Some(100000000
7) }, failure reason Some(FailureInfo { revert_code: 3, revert_reason: "o1", gas_used: Some(86513), gas_limit: 4000000 })
thread 'tokio-runtime-worker' panicked at /home/crypto/zksync-era/core/lib/zksync_core/src/eth_sender/eth_tx_manager.rs:487:9:
We can't operate after tx fail
stack backtrace:
   0:     0x564e22d0593c - std::backtrace_rs::backtrace::libunwind::trace::h68b3f03db065435f
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564e22d0593c - std::backtrace_rs::backtrace::trace_unsynchronized::hcc29d957a519c467
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564e22d0593c - std::sys_common::backtrace::_print_fmt::h51e5567c7446b80e
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x564e22d0593c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h54890bb4d0b3c330
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x564e22d341fc - core::fmt::rt::Argument::fmt::heae7cd8ccc900aeb
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/fmt/rt.rs:138:9
   5:     0x564e22d341fc - core::fmt::write::hc761729f1163b685
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/fmt/mod.rs:1094:21
   6:     0x564e22d0182e - std::io::Write::write_fmt::hd8de790e313b58ee
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/io/mod.rs:1714:15
   7:     0x564e22d05724 - std::sys_common::backtrace::_print::h1b2adaff5c947b3b
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x564e22d05724 - std::sys_common::backtrace::print::hf6a9b81f93e62890
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x564e22d073da - std::panicking::panic_hook_with_disk_dump::{{closure}}::h663629ab1a73f13e
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:278:22
  10:     0x564e22d070c7 - std::panicking::panic_hook_with_disk_dump::h7dc7628c0cba33b1
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:312:9
  11:     0x564e22d079db - std::panicking::default_hook::h4cb3ec769d1db09c
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:239:5
  12:     0x564e22d079db - std::panicking::rust_panic_with_hook::hdd1521f6ef2543b7
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:729:13
  13:     0x564e20edb09a - std::panicking::begin_panic::{{closure}}::h268d97f7377683a8 
  14:     0x564e20ed49a6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6f585e0a223494d5
  15:     0x564e20b1759a - std::panicking::begin_panic::haa87395fe3e3207f
  16:     0x564e20f6a15a - zksync_core::eth_sender::eth_tx_manager::EthTxManager<E,G>::monitor_inflight_transactions::{{closure}}::h4d332ad980058130
  17:     0x564e20fd1905 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hc503ca5963c0e1cf
  18:     0x564e20da9bab - zksync_core::eth_sender::eth_tx_manager::EthTxManager<E,G>::run::{{closure}}::h96e2c710d2c4f358
  19:     0x564e20e4b25f - tokio::runtime::task::core::Core<T,S>::poll::h8790c1b22391148a
  20:     0x564e2147ccf1 - tokio::runtime::task::harness::Harness<T,S>::poll::hdf215feec43c1797
  21:     0x564e22b493ac - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h2113e949c4e27260
  22:     0x564e22b483e4 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h980ffa35546d96f9
  23:     0x564e22b2f987 - tokio::runtime::context::scoped::Scoped<T>::set::h81e33d22ffcf34e1
  24:     0x564e22b47649 - tokio::runtime::scheduler::multi_thread::worker::run::hfd9dbe0be98b8b93
  25:     0x564e22b2bd9a - tokio::runtime::task::core::Core<T,S>::poll::had9134d62db84041
  26:     0x564e22b252be - tokio::runtime::task::harness::Harness<T,S>::poll::hac306cafd952b0d3
  27:     0x564e22b292fd - tokio::runtime::blocking::pool::Inner::run::h769a4e2560434b97
  28:     0x564e22b3d385 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha748c2bcd2fb6c94
  29:     0x564e22b4d869 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0a6821c79520efa2
  30:     0x564e22d0aba5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7bbddabb40181918
                              at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/alloc/src/boxed.rs:2007:9
  31:     0x564e22d0aba5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4e41f7977be0d993
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/alloc/src/boxed.rs:2007:9
  32:     0x564e22d0aba5 - std::sys::unix::thread::Thread::new::thread_start::h6eb72cf9b874b24b
                               at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/sys/unix/thread.rs:108:17
  33:     0x7fb011294ac3 - <unknown>
  34:     0x7fb011326a40 - <unknown>
  35:                0x0 - <unknown>
2023-11-07T20:00:25.836756Z  INFO zksync_utils::wait_for_tasks: One of the tokio actors unexpectedly finished with error: We can't operate after tx fail
2023-11-07T20:00:25.836888Z  INFO zksync_core::proof_data_handler: Stop signal received, proof data handler server is shutting down
2023-11-07T20:00:25.836931Z  INFO zksync_core::metadata_calculator::updater: Stop signal received, metadata_calculator is shutting down
2023-11-07T20:00:25.836987Z  INFO vise_exporter::exporter: Stop signal received, Prometheus metrics exporter is shutting down
2023-11-07T20:00:25.836997Z  INFO zksync_core::proof_data_handler: Proof data handler server shut down
2023-11-07T20:00:25.837022Z  INFO zksync_storage::db: Waiting for all the RocksDB instances to be dropped, 1 remaining
2023-11-07T20:00:25.837106Z  INFO vise_exporter::exporter: Prometheus metrics exporter server shut down
2023-11-07T20:00:25.841299Z  INFO zksync_core::api_server::web3: Stop signal received, WS JSON-RPC server is shutting down
2023-11-07T20:00:25.844588Z  INFO zksync_core::api_server::execution_sandbox: VM concurrency limiter closed
2023-11-07T20:00:25.845098Z  INFO zksync_storage::db: All the RocksDB instances are dropped
2023-11-07T20:00:25.847049Z  INFO zksync_core::state_keeper::mempool_actor: Stop signal received, mempool is shutting down
2023-11-07T20:00:25.841444Z  INFO zksync_core::api_server::web3: Stop signal received, HTTP JSON-RPC server is shutting down
2023-11-07T20:00:25.847975Z  INFO zksync_core::api_server::execution_sandbox: VM concurrency limiter closed
2023-11-07T20:00:25.865210Z  INFO zksync_core::api_server::web3: HTTP JSON-RPC server stopped
2023-11-07T20:00:25.865254Z  INFO zksync_core::api_server::web3: VM execution on HTTP JSON-RPC server stopped
2023-11-07T20:00:25.921971Z  INFO zksync_core::api_server::web3::pubsub_notifier: Stop signal received, pubsub_tx_notifier is shutting down
2023-11-07T20:00:25.923987Z  INFO zksync_core::api_server::web3::pubsub_notifier: Stop signal received, pubsub_block_notifier is shutting down
2023-11-07T20:00:25.931349Z  INFO zksync_core::api_server::web3::pubsub_notifier: Stop signal received, pubsub_logs_notifier is shutting down
2023-11-07T20:00:25.938942Z  INFO zksync_core::api_server::web3: WS JSON-RPC server stopped
2023-11-07T20:00:25.939085Z  INFO zksync_core::api_server::web3: VM execution on WS JSON-RPC server stopped
2023-11-07T20:00:25.955319Z  INFO zksync_core::eth_watch: Stop signal received, eth_watch is shutting down
2023-11-07T20:00:26.000426Z  INFO zksync_core::eth_sender::eth_tx_aggregator: Stop signal received, eth_tx_aggregator is shutting down
2023-11-07T20:00:26.135810Z  INFO zksync_core::state_keeper::keeper: Stop signal received, state keeper is shutting down
2023-11-07T20:00:29.715661Z  INFO zksync_core::l1_gas_price::gas_adjuster: Stop signal received, gas_adjuster is shutting down
2023-11-07T20:00:30.846222Z  INFO zksync_core::api_server::healthcheck: Stop signal received, healthcheck server is shutting down
2023-11-07T20:00:30.846312Z  INFO zksync_core::api_server::healthcheck: Healthcheck server shut down
2023-11-07T20:00:30.846346Z  INFO zksync_server: Stopped
```

**Comment by perekopskiy** [comment]
@JayT106 Panic happens because you are sending a deposit from the operator address (`ETH_SENDER_SENDER_OPERATOR_COMMIT_ETH_ADDR` by default is equal to 0xde03a0B5963f75f1C8485B355fF6D30f3093BDE7). `eth_tx_manager` is working with assumption that it's the only entity who sends transactions from operator address.

If you try making a deposit from some address different from 0xde03a0B5963f75f1C8485B355fF6D30f3093BDE7, then it should work
