### ISSUE TITLE
 I run 'zk f cargo +nightly run --release --bin zksync_prover'，I got error

### ISSUE THREAD

**Issue by brownsend** [matter-labs/zksync-era#49]
I run  'zk init'  and run  'zk server',it is ok. Then I run 'zk f cargo +nightly run --release --bin zksync_prover',I got error
whether I need to configure environment variables ?

![image](https://github.com/matter-labs/zksync-era/assets/121163538/aa355ebc-9ca7-42af-838f-875deedf6d91)

this is my directory, " zksync-era/target/release"

![image](https://github.com/matter-labs/zksync-era/assets/121163538/ca50b9cf-2c9f-4fe3-986a-14fcf0b3336d)

**Comment by Zhenyazhd** [comment]
Hi, I faced the same error. Maybe you've made some progress on it?

**Comment by l0gun0v** [comment]
> 

Do you run it from core/bin/prover folder ?

**Comment by Zhenyazhd** [comment]
I tried but then it ends up with this error: "error[E0422]: cannot find struct, variant or union type `LineColumn` in crate `proc_macro`"

**Comment by l0gun0v** [comment]
> I tried but then it ends up with this error: "error[E0422]: cannot find struct, variant or union type `LineColumn` in crate `proc_macro`"

So, I am trying to fix some errors to (error: to use a constant of type `TypeId` in a pattern, `TypeId` must be annotated with `#[derive(PartialEq, Eq)]`
) .

But it fixes error that post's author has.

**Comment by l0gun0v** [comment]
> I tried but then it ends up with this error: "error[E0422]: cannot find struct, variant or union type `LineColumn` in crate `proc_macro`"

cargo update -p proc-macro2@1.0.52

**Comment by Zhenyazhd** [comment]
thanks! Now i have the same error as you mentioned above

**Comment by l0gun0v** [comment]
> thanks! Now i have the same error as you mentioned above

Please send some your WhatsApp or Telegram to this mail, Because I don't want to spam here) logunov.dennis@gmail.com

**Comment by olehnikolaiev** [comment]
hello @l0gun0v ! got an error running the same command. it was executed in `core/bin/prover` folder 
```
error: failed to run custom build command for `gpu-ffi v0.1.0 (https://github.com/matter-labs/era-heavy-ops-service.git?branch=v1.3.3#522dcebc)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/zksync/core/bin/prover/target/release/build/gpu-ffi-91d210befec11d6f/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'not yet implemented: set BELLMAN_CUDA_DIR=$PWD', /home/.cargo/git/checkouts/era-heavy-ops-service-54439bd555659c38/522dceb/gpu-ffi/build.rs:16:9
  stack backtrace:
     0:     0x55ee931e9371 - std::backtrace_rs::backtrace::libunwind::trace::h81b3ec7e24504ef6
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x55ee931e9371 - std::backtrace_rs::backtrace::trace_unsynchronized::h06b108a8ac6d8321
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55ee931e9371 - std::sys_common::backtrace::_print_fmt::hddd2a53a0a5c1518
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x55ee931e9371 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8286d7e4527fc2ef
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x55ee9321432c - core::fmt::rt::Argument::fmt::h8fd89467fbfd7337
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/core/src/fmt/rt.rs:138:9
     5:     0x55ee9321432c - core::fmt::write::h51943d696b01a399
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/core/src/fmt/mod.rs:1094:21
     6:     0x55ee931e603e - std::io::Write::write_fmt::h917c762025be867c
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/io/mod.rs:1714:15
     7:     0x55ee931e9185 - std::sys_common::backtrace::_print::h80196d93ed8f3afc
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x55ee931e9185 - std::sys_common::backtrace::print::hfc2f9057cab2ca91
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x55ee931ea91a - std::panicking::panic_hook_with_disk_dump::{{closure}}::h044c489edf02dba6
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:278:22
    10:     0x55ee931ea5b3 - std::panicking::panic_hook_with_disk_dump::hc012686c97dee411
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:312:9
    11:     0x55ee931eaf1b - std::panicking::default_hook::h38859ccab48a30da
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:239:5
    12:     0x55ee931eaf1b - std::panicking::rust_panic_with_hook::hbec509e90f57ee70
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:729:13
    13:     0x55ee931eadd1 - std::panicking::begin_panic_handler::{{closure}}::h24e3657f27ebdc7b
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:619:13
    14:     0x55ee931e97d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h0fb71023354b550a
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/sys_common/backtrace.rs:151:18
    15:     0x55ee931eab62 - rust_begin_unwind
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:617:5
    16:     0x55ee92d9b2f3 - core::panicking::panic_fmt::haa55128da9cd75d4
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/core/src/panicking.rs:67:14
    17:     0x55ee92d9d630 - build_script_build::main::hd746e0e88f711aef
    18:     0x55ee92d9c473 - core::ops::function::FnOnce::call_once::h45d2f6e7004c34a0
    19:     0x55ee92d9bb26 - std::sys_common::backtrace::__rust_begin_short_backtrace::h00472aa3063832d9
    20:     0x55ee92d9c1a9 - std::rt::lang_start::{{closure}}::h4a8b0ab683e3f8f5
    21:     0x55ee931e1d7b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2240a7a2e9d7937c
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/core/src/ops/function.rs:284:13
    22:     0x55ee931e1d7b - std::panicking::try::do_call::h6d94044a2dac5948
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:524:40
    23:     0x55ee931e1d7b - std::panicking::try::hc16721a649b6347e
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:488:19
    24:     0x55ee931e1d7b - std::panic::catch_unwind::ha5ec842243b12570
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panic.rs:142:14
    25:     0x55ee931e1d7b - std::rt::lang_start_internal::{{closure}}::h718bb866ab67d475
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/rt.rs:148:48
    26:     0x55ee931e1d7b - std::panicking::try::do_call::hca57e22a5a3d68fb
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:524:40
    27:     0x55ee931e1d7b - std::panicking::try::hfd3cbded253620e6
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panicking.rs:488:19
    28:     0x55ee931e1d7b - std::panic::catch_unwind::h1fa2ff1a7cb410d5
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/panic.rs:142:14
    29:     0x55ee931e1d7b - std::rt::lang_start_internal::h1dfc41da9ec083ca
                                 at /rustc/864bdf7843e1ceabc824ed86d97006acad6af643/library/std/src/rt.rs:148:20
    30:     0x55ee92d9c187 - std::rt::lang_start::hd32eb1f76941e72e
    31:     0x55ee92d9dfa5 - main
    32:     0x7f9748629d90 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    33:     0x7f9748629e40 - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:392:3
    34:     0x55ee92d9ba55 - _start
    35:                0x0 - <unknown>
```

**Comment by popzxc** [comment]
Please note that prover isn't optimized for running locally right now, however we're working on the documentation to make it possible to run it locally (including HW requirements). Stay tuned.
