### ISSUE TITLE
Error when run `zk init`

### ISSUE THREAD

**Issue by Niet-Pham** [matter-labs/zksync-era#51]
I ran `zk init` and I got this error
```
> Running server genesis setup
    Finished release [optimized] target(s) in 0.57s
     Running `target/release/zksync_server --genesis`
2023-06-21T07:49:51.442941Z  INFO zksync_core::genesis: running regenesis
thread 'main' panicked at 'Can't read .zbin bytecode at "/home/developer/zksync-era/etc/system-contracts/contracts/precompiles/artifacts/Keccak256.yul/Keccak256.yul.zbin": No such file or directory (os error 2)', core/lib/contracts/src/lib.rs:195:31
stack backtrace:
   0:     0x559f9fe5423a - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x559f9fe5423a - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x559f9fe5423a - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x559f9fe5423a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x559f9fe7a84e - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x559f9fe4df25 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x559f9fe54005 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x559f9fe54005 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x559f9fe55c5f - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x559f9fe5599b - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x559f9fe5636c - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x559f9fe56109 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0x559f9fe546ec - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x559f9fe55e12 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x559f9dee1793 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x559f9f6f9657 - zksync_contracts::read_zbin_bytecode::h019f7e40fb83fe26
  16:     0x559f9f6f8f33 - zksync_contracts::read_sys_contract_bytecode::h67501b418aa0b9d7
  17:     0x559f9f368b64 - core::array::collect_into_array_unchecked::h7a21f436668d8136
  18:     0x559f9f378df1 - core::ops::function::FnOnce::call_once::h3517cf1cc6508053
  19:     0x559f9f37a95a - once_cell::imp::OnceCell<T>::initialize::{{closure}}::h611c9878b595dcb1
  20:     0x559f9fde8c61 - once_cell::imp::initialize_or_wait::hffbd1dbdb754c2ad
  21:     0x559f9dea2e12 - once_cell::imp::OnceCell<T>::initialize::hf64de522f6baed2c
  22:     0x559f9f37b5c4 - zksync_types::system_contracts::get_system_smart_contracts::h42706fb6c1e723be
  23:     0x559f9e4e47fd - zksync_core::genesis::create_genesis_block::h16e2b680098eaf23
  24:     0x559f9df05aed - zksync_core::genesis_init::{{closure}}::hfa6fa76183d856ac
  25:     0x559f9df4b172 - tokio::runtime::park::CachedParkThread::block_on::h6daa800f1c4d158b
  26:     0x559f9e184ca9 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h6f6535201995ecdf
  27:     0x559f9e1c43c0 - tokio::runtime::runtime::Runtime::block_on::h1b8f393dc36173d0
  28:     0x559f9e0d9daf - zksync_server::main::h09c7414d2d63b222
  29:     0x559f9e005803 - std::sys_common::backtrace::__rust_begin_short_backtrace::h19649a926bdc1402
  30:     0x559f9df2a85d - std::rt::lang_start::{{closure}}::hc44effbbc306b0e0
  31:     0x559f9fe44dfc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfa1c3687c9a20bb8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
  32:     0x559f9fe44dfc - std::panicking::try::do_call::h0497133ebe1341e5
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  33:     0x559f9fe44dfc - std::panicking::try::h6c3de05c7ca5d07f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  34:     0x559f9fe44dfc - std::panic::catch_unwind::h969058ecb5334b30
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  35:     0x559f9fe44dfc - std::rt::lang_start_internal::{{closure}}::h0de6d98cafb42a58
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
  36:     0x559f9fe44dfc - std::panicking::try::do_call::h77301dcf43953993
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  37:     0x559f9fe44dfc - std::panicking::try::h45b05523a2fe135a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  38:     0x559f9fe44dfc - std::panic::catch_unwind::hd95cea544b2b9bd2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  39:     0x559f9fe44dfc - std::rt::lang_start_internal::hd16e6ff7bf05a444
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  40:     0x559f9e0d9e95 - main
  41:     0x7f48dbeec083 - __libc_start_main
  42:     0x559f9df0248e - _start
  43:                0x0 - <unknown>
  ```

**Comment by louisliu2048** [comment]
Yes, same error for me.
> Running server genesis setup
    Finished release [optimized] target(s) in 1.36s
     Running `target/release/zksync_server --genesis`
2023-06-28T02:50:44.239005Z  INFO zksync_core::genesis: running regenesis
thread 'main' panicked at 'Can't read .zbin bytecode at "/xxx/zksync-era/etc/system-contracts/contracts/precompiles/artifacts/Keccak256.yul/Keccak256.yul.zbin": No such file or directory (os error 2)', core/lib/contracts/src/lib.rs:195:31
stack backtrace:
   0:        0x1048dac56 - std::backtrace_rs::backtrace::libunwind::trace::h0b8f2febfa937669
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1048dac56 - std::backtrace_rs::backtrace::trace_unsynchronized::h4f74cd180825fa00
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1048dac56 - std::sys_common::backtrace::_print_fmt::hdf2aee729151be64

**Comment by louisliu2048** [comment]
1. fix `regex conflict `error
 ```
cargo update --package regex
```

2. fix  `Can't read .zbin bytecode ` error
```
git submodule update --init
git submodule update --remote
```
3. fix `incorrect contract casing` error
follow: https://github.com/emilianobonassi/zksync-era/commit/91a11c0be7b980985b962e228077334b78e1d3ef 
rename two sol file name: 
```
zksync/contracts/bridge/L2WETH.sol ->  zksync/contracts/bridge/L2Weth.sol 
zksync/contracts/bridge/interfaces/IL2WETH.sol  -> zksync/contracts/bridge/interfaces/IL2Weth.sol
```

**Comment by lisuxiaoqi** [comment]
> IL2Weth.sol
Could it be merge to the main branch quickly for the casing issue. it's annoying~
