### ISSUE TITLE
`matterlabs/local-node:latest2.0` fails to setup local node

### ISSUE THREAD

**Issue by haraldh** [matter-labs/zksync-era#637]
#### 📝 Description

Try to setup a dev environment using `zksync-cli`.

#### 🔄 Reproduction Steps

```
❯ npx zksync-cli dev config
? Node type to use Dockerized node
? Additional modules to use (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
 ◯ Portal - DApp with Wallet and Bridge functionality
❯◯ Block Explorer - zkSync block explorer UI and API

❯ npx zksync-cli dev start
```

```
❯ docker image ls
REPOSITORY              TAG         IMAGE ID       CREATED        SIZE
matterlabs/local-node   latest2.0   944842ed4d32   10 days ago    3.14GB
```

Looking at the logs of `matterlabs/local-node:latest2.0` , I see:
```
[…]
CONTRACTS_L1_ERC20_BRIDGE_PROXY_ADDR=0x57Ff05Fa631c446d181498df8Ac4A3CdAFCc5a76
Error: TypeError: Cannot read properties of undefined (reading 'address')
    at Deployer.<anonymous> (/contracts/ethereum/src.ts/deploy.ts:318:92)
    at step (/contracts/ethereum/src.ts/deploy.ts:33:23)
    at Object.next (/contracts/ethereum/src.ts/deploy.ts:14:53)
    at /contracts/ethereum/src.ts/deploy.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/contracts/ethereum/src.ts/deploy.ts:4:12)
    at Deployer.deployWethBridgeImplementation (/contracts/ethereum/src.ts/deploy.ts:390:16)
    at Deployer.<anonymous> (/contracts/ethereum/src.ts/deploy.ts:439:16)
    at step (/contracts/ethereum/src.ts/deploy.ts:33:23)
    at Object.next (/contracts/ethereum/src.ts/deploy.ts:14:53)
^Merror Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Skip contract verification on localhost

[…]

> Initializing governance
$ ts-node scripts/initialize-governance.ts
Using deployer wallet: 0x52312AD6f01657413b2eaE9287f6B9ADaD93D5FE
Using gas price: 1.000003115 gwei
Error: <ref *1> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNP
REDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x
52312AD6f01657413b2eaE9287f6B9ADaD93D5FE","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","h
ex":"0x596841a4"},"to":"0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9","data":"0x8f283970000000000000000000000000b8a8ee67b0bee0832ef8a83ad156b960
5e4f8277","type":2,"accessList":null},"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":
89,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\
"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x596841a4\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x52312ad6f01657413b2eae9287f6
b9adad93d5fe\",\"to\":\"0x5e6d086f5ec079adff4fb3774cdf3e8d6a34f7e9\",\"data\":\"0x8f283970000000000000000000000000b8a8ee67b0bee0832ef8a83ad156
b9605e4f8277\"}],\"id\":89,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://geth:8545"}}, tx={"data":"0x8f28397000000000000000000000
0000b8a8ee67b0bee0832ef8a83ad156b9605e4f8277","to":{},"from":"0x52312AD6f01657413b2eaE9287f6B9ADaD93D5FE","type":2,"maxFeePerGas":{"type":"Big
Number","hex":"0x596841a4"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPRED
ICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)
    at Logger.makeError (/contracts/ethereum/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/contracts/ethereum/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at /contracts/ethereum/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:301:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 7) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTA
BLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x52312AD6f01657413b2eaE9287f6B9ADaD93D5FE","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x596841a4"},"to":"0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9","data":"0x8f283970000000000000000000000000b8a8ee67b0bee0832ef8a83ad156b9605e4f8277","type":2,"accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":89,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x596841a4\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x52312ad6f01657413b2eae9287f6b9adad93d5fe\",\"to\":\"0x5e6d086f5ec079adff4fb3774cdf3e8d6a34f7e9\",\"data\":\"0x8f283970000000000000000000000000b8a8ee67b0bee0832ef8a83ad156b9605e4f8277\"}],\"id\":89,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://geth:8545"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
      at Logger.makeError (/contracts/ethereum/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (/contracts/ethereum/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at checkError (/contracts/ethereum/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:78:20)
      at JsonRpcProvider.<anonymous> (/contracts/ethereum/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:20)
      at step (/contracts/ethereum/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
      at Object.throw (/contracts/ethereum/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
      at rejected (/contracts/ethereum/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'execution reverted',
    code: 'UNPREDICTABLE_GAS_LIMIT',
    code: 'UNPREDICTABLE_GAS_LIMIT',
    method: 'estimateGas',
    transaction: {
      from: '0x52312AD6f01657413b2eaE9287f6B9ADaD93D5FE',
      maxPriorityFeePerGas: [BigNumber],
      maxFeePerGas: [BigNumber],
      to: '0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9',
      data: '0x8f283970000000000000000000000000b8a8ee67b0bee0832ef8a83ad156b9605e4f8277',
      type: 2,
      accessList: null
    },
    error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":89,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x596841a4\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x52312ad6f01657413b2eae9287f6b9adad93d5fe\",\"to\":\"0x5e6d086f5ec079adff4fb3774cdf3e8d6a34f7e9\",\"data\":\"0x8f283970000000000000000000000000b8a8ee67b0bee0832ef8a83ad156b9605e4f8277\"}],\"id\":89,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://geth:8545", code=SERVER_ERROR, version=web/5.7.1)
        at Logger.makeError (/contracts/ethereum/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
        at Logger.throwError (/contracts/ethereum/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
        at /contracts/ethereum/node_modules/@ethersproject/web/src.ts/index.ts:341:28
        at step (/contracts/ethereum/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/contracts/ethereum/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/contracts/ethereum/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      reason: 'processing response error',
      code: 'SERVER_ERROR',
      body: '{"jsonrpc":"2.0","id":89,"error":{"code":-32000,"message":"execution reverted"}}\n',
      error: [Error],
      requestBody: '{"method":"eth_estimateGas","params":[{"type":"0x2","maxFeePerGas":"0x596841a4","maxPriorityFeePerGas":"0x59682f00","from":"0x52312ad6f01657413b2eae9287f6b9adad93d5fe","to":"0x5e6d086f5ec079adff4fb3774cdf3e8d6a34f7e9","data":"0x8f283970000000000000000000000000b8a8ee67b0bee0832ef8a83ad156b9605e4f8277"}],"id":89,"jsonrpc":"2.0"}',
      requestMethod: 'POST',
      url: 'http://geth:8545'
    }
  },
  tx: {
    data: '0x8f283970000000000000000000000000b8a8ee67b0bee0832ef8a83ad156b9605e4f8277',
    to: Promise { '0x5E6D086F5eC079ADFF4FB3774CDf3e8D6a34F7E9' },
    from: '0x52312AD6f01657413b2eaE9287f6B9ADaD93D5FE',
    type: 2,
    maxFeePerGas: BigNumber { _hex: '0x596841a4', _isBigNumber: true },
    maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    nonce: Promise { 22 },
    gasLimit: Promise { <rejected> [Circular *1] },
    chainId: Promise { 9 }
  }
}
^Merror Command failed with exit code 1.
✔ Initializing governance done (6336ms)
Done in 92.44s.
yarn run v1.22.21
$ node build/index.js f yarn --cwd /infrastructure/local-setup-preparation start
$ ts-node ./src/index.ts
/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:14:10 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

14     if (!process.env.CONTRACTS_DIAMOND_PROXY_ADDR) {
            ~~~~~~~
src/index.ts:22:42 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

22     const contract = new ethers.Contract(process.env.CONTRACTS_DIAMOND_PROXY_ADDR, utils.ZKSYNC_MAIN_ABI, ethProvider);
                                            ~~~~~~~
src/index.ts:31:46 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

31         const contract = new ethers.Contract(process.env.CONTRACTS_DIAMOND_PROXY_ADDR, utils.ZKSYNC_MAIN_ABI, wallet);
                                                ~~~~~~~

    at createTSError (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/infrastructure/local-setup-preparation/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2580, 2580, 2580 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by haraldh** [comment]
https://hub.docker.com/layers/matterlabs/local-node/latest2.0/images/sha256-f6c21f9db5cbb5c04783e9aaa460d7ef7f1315859fe826946e980072cecc286c?context=explore

seems to work now! Thank you!
