### ISSUE TITLE
error while using zk init command its not pulling out the images correctly

### ISSUE THREAD

**Issue by DSHIVAAY-23** [matter-labs/zksync-era#64]
zk init

-------------------------
> Creating docker volumes
✔ Creating docker volumes done (0ms)

----------------
> Pulling images
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

**Comment by hatemosphere** [comment]
this works for all our developers with latest head of dev branch, both on MacOS and Linux workstations. so the issue you were experiencing was either related to the specifics or your env or using old broken branch. please update to yhe latest code base, install latest Docker and other dependencies, and try again. please free to reopen if it still does not work.
