### ISSUE TITLE
start the server failed

### ISSUE THREAD

**Issue by bradyjoestar** [matter-labs/zksync-era#665]
after run the `zk stack init`, I try to start the server and met the following bug:
```
--------------
> Start server
✔ Do you want to start your hyperchain server now? · Yes (default components)
    Finished release [optimized] target(s) in 0.35s
     Running `target/release/zksync_server --components=http_api,eth,data_fetcher,state_keeper,housekeeper,tree_lightweight`
2023-12-12T10:36:20.141592Z  INFO zksync_server: No sentry URL was provided
thread 'main' panicked at /root/zksync-era/core/lib/zksync_core/src/lib.rs:187:10:
failed to build connection_pool: Failed connecting to database

Caused by:
    0: error communicating with database: failed to lookup address information: Temporary failure in name resolution
    1: failed to lookup address information: Temporary failure in name resolution

Stack backtrace:
   0: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
   1: zksync_dal::connection::ConnectionPoolBuilder::build::{{closure}}
   2: zksync_server::main::{{closure}}
   3: tokio::runtime::park::CachedParkThread::block_on
   4: tokio::runtime::runtime::Runtime::block_on
   5: zksync_server::main
   6: std::sys_common::backtrace::__rust_begin_short_backtrace
   7: std::rt::lang_start::{{closure}}
   8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/core/src/ops/function.rs:284:13
   9: std::panicking::try::do_call
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:524:40
  10: std::panicking::try
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:488:19
  11: std::panic::catch_unwind
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panic.rs:142:14
  12: std::rt::lang_start_internal::{{closure}}
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/rt.rs:148:48
  13: std::panicking::try::do_call
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:524:40
  14: std::panicking::try
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panicking.rs:488:19
  15: std::panic::catch_unwind
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/panic.rs:142:14
  16: std::rt::lang_start_internal
             at /rustc/5c6a7e71cd66705c31c9af94077901a220f0870c/library/std/src/rt.rs:148:20
  17: main
```

**Comment by yakifugu** [comment]
I met the same error. Any help?

**Comment by wjw12** [comment]
I met this error and somehow resolved it (forgot how exactly)

Check this:
`docker ps` should include `postgres` and `matterlabs/geth:latest` container up and running (or any other L1 node), and make sure geth port 8545 is open.

**Comment by nonameb3** [comment]
Any update? I got the same error.

**Comment by nonameb3** [comment]
Try this [answer](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/260).

**Comment by jespercv** [comment]
was there any solution into this? also had the same error.

**Comment by pc1223** [comment]
This issue can be closed
